AllCops:
  TargetRubyVersion: 2.7.1

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Gemspec/RequiredRubyVersion:
  Enabled: false
